### PR TITLE
Added Bosnian Translations

### PR DESCRIPTION
**Pull request by SecularSteve**
Missed a spot in the Fastlane Descriptions.

If you need me to translate all of the changelogs too, I'll try to do it as quick as possible if they are that important.

Apologies for doing it manually. I didn't know it would lead to those complications. Would be useful if you put that in #9 too (in my opinion).

الله أكبر. باركوا لكم جميعا.

### CODE REVIEW

**Comment by meypod** [comment]
sorry, no need to translate changelogs, please remove them

**Comment by SecularSteve** [comment]
done

**Comment by meypod** [comment]
can you resolve the issue I pointed out on short description ?

**Comment by SecularSteve** [comment]
done

**Comment by meypod** [comment]
thanks

**Pull request merged**
